# Change these first
owner: pwmonitor # Your GitHub organization or username, where this repository lives
repo: monikosi # The name of this repository

sites:
  - name: kosilum.com
    url: https://www.kosilum.com
  - name: kosilum.com-http
    url: http://www.kosilum.com
  - name: kosilight.uk
    url: https://kosilight.uk
  - name: kosilight.uk-http
    url: http://kosilight.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monikosi
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: monitoring for KOSI
  introTitle: "monitoring for kosilum"
  introMessage: monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
